# Generated by Django 4.1.3 on 2022-12-13 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_article_category_alter_article_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(default='null', upload_to='media/articles', verbose_name='imagen'),
        ),
    ]
